---
- name: Test cv_container_v3 for image bundle
  hosts: CloudVision
  connection: local
  gather_facts: false
  collections:
    - arista.cvp
  vars:

    ansible_command_timeout: 1200
    ansible_connect_timeout: 600

    TOPOLOGY_3_TIER:
      TEAM01:
        parentContainerName: Tenant
      TEAM01_DC:
        parentContainerName: TEAM01
      TEAM01_LEAFS:
        parentContainerName: TEAM01_DC
        imageBundle: EOS-4.25.4M

    image_name: "EOS-4.25.4M.swi" # image file should be present

    IMAGE_CONTAINER:
      TEAM01_LEAFS:
        parentContainerName: TEAM01_DC
        imageBundle: EOS-4.25.4M

    CHANGE_IMAGE_CONTAINER_Test_bundle:
      TEAM01_LEAFS:
        parentContainerName: TEAM01_DC
        imageBundle: Test_bundle

    REMOVE_IMAGE:
      TEAM01_LEAFS:
        parentContainerName: TEAM01_DC
        imageBundle: ''

  tasks:

  # TC3 - Create a 3 tier topology and attach image bundles to one of the containers and remove it.
  # Testing:
  #       1. Creating Test_bundle
  #       2. Adding image bundles
  #       3. Change in image bundles with apply_mode: loose
  #       4. Change in image bundles with apply_mode: strict
  #       5. Removal of container which contains image bundles.
  #       6. Remove entire 3 tier topology in which image bundles is attached to one of the containers

    - name: Build Container Topology On {{inventory_hostname}} with image bundle
      arista.cvp.cv_container_v3:
        topology: '{{TOPOLOGY_3_TIER}}'
      register: Build_TOPO_3_TIER

    - name: Testing Build Container
      assert:
        that:
          - Build_TOPO_3_TIER.container_added.changed == true
          - Build_TOPO_3_TIER.container_added.container_added_count == 3
          - Build_TOPO_3_TIER.container_added.container_added_list == ["TEAM01", "TEAM01_DC", "TEAM01_LEAFS"]
          - Build_TOPO_3_TIER.container_added.success == true
          - Build_TOPO_3_TIER.bundle_attached.changed == true
          - Build_TOPO_3_TIER.bundle_attached.bundle_attached_count == 1
          - Build_TOPO_3_TIER.bundle_attached.bundle_attached_list == ["EOS-4.25.4M"]
          - Build_TOPO_3_TIER.bundle_attached.success == true

    - name: "Create a bundle for test"
      arista.cvp.cv_image_v3:
        mode: bundle
        action: add
        bundle_name: Test_bundle
        image_list:
          - "{{image_name}}"
      register: CREATE_BUNDLE_DATA

    - name: "Testing create bundle"
      assert:
        that:
          - CREATE_BUNDLE_DATA.data.data == "Bundle : Test_bundle successfully created"

    - name: "Change Image"
      arista.cvp.cv_container_v3:
        topology: '{{CHANGE_IMAGE_CONTAINER_Test_bundle}}'
      register: CHANGE_IMAGE_Test_bundle

    - name: "Testing Change Image"
      assert:
        that:
            - CHANGE_IMAGE_Test_bundle.bundle_attached.changed == true
            - CHANGE_IMAGE_Test_bundle.bundle_attached.bundle_attached_count == 1
            - CHANGE_IMAGE_Test_bundle.bundle_attached.bundle_attached_list == ["Test_bundle"]
            - CHANGE_IMAGE_Test_bundle.bundle_attached.success == true

    - name: "Remove Image"
      arista.cvp.cv_container_v3:
        topology: '{{REMOVE_IMAGE}}'
        apply_mode: strict
      register: IMAGE_REMOVE

    - name: "Testing Remove Image"
      assert:
        that:
            - IMAGE_REMOVE.bundle_detached.changed == true
            - IMAGE_REMOVE.bundle_detached.bundle_detached_count == 1
            - IMAGE_REMOVE.bundle_detached.bundle_detached_list == ["Test_bundle"]
            - IMAGE_REMOVE.bundle_detached.success == true


    - name: "Remove Container Topology On {{inventory_hostname}} With Image"
      arista.cvp.cv_container_v3:
        topology: '{{IMAGE_CONTAINER}}'
        state: absent
      register: IMAGE_CONTAINER_REMOVE

    - name: "Testing Remove Container With Image"
      assert:
        that:
          - IMAGE_CONTAINER_REMOVE.container_deleted.changed == true
          - IMAGE_CONTAINER_REMOVE.container_deleted.container_deleted_count == 1
          - IMAGE_CONTAINER_REMOVE.container_deleted.container_deleted_list == ["TEAM01_LEAFS"]
          - IMAGE_CONTAINER_REMOVE.container_deleted.success == true

    - name: "Add Container Topology On {{inventory_hostname}} With Image"
      arista.cvp.cv_container_v3:
        topology: '{{IMAGE_CONTAINER}}'

    - name: Clean-up Topology
      arista.cvp.cv_container_v3:
        topology: '{{TOPOLOGY_3_TIER}}'
        state: absent
      register: DELETE_TOPOLOGY

    - name: Clean-up Bundle
      arista.cvp.cv_image_v3:
        mode: bundle
        action: remove
        bundle_name: Test_bundle
        image_list:
          - "{{image_name}}"
      register: DELETE_BUNDLE

    - name: "Testing Clean-up"
      assert:
        that:
          - DELETE_TOPOLOGY.container_deleted.changed == true
          - DELETE_TOPOLOGY.container_deleted.container_deleted_count == 3
          - DELETE_TOPOLOGY.container_deleted.container_deleted_list == ["TEAM01_LEAFS", "TEAM01_DC", "TEAM01"]
          - DELETE_TOPOLOGY.container_deleted.success == true
          - DELETE_BUNDLE.data.data == "success"
