---
- name: Test cv_container_v3 for image bundle
  hosts: CloudVision
  connection: local
  gather_facts: false
  collections:
    - arista.cvp
  vars:

    ansible_command_timeout: 1200
    ansible_connect_timeout: 600

    topology_3_tier:
      TEAM01:
        parentContainerName: Tenant
      TEAM01_DC:
        parentContainerName: TEAM01
      TEAM01_LEAFS:
        parentContainerName: TEAM01_DC
        imageBundle: vEOS-lab-4.30.1F

    image_name: "vEOS-lab-4.30.1F.swi" # image file should be present

    image_container:
      TEAM01_LEAFS:
        parentContainerName: TEAM01_DC
        imageBundle: vEOS-lab-4.30.1F

    change_image_container_test_bundle:
      TEAM01_LEAFS:
        parentContainerName: TEAM01_DC
        imageBundle: Test_bundle

    remove_image:
      TEAM01_LEAFS:
        parentContainerName: TEAM01_DC
        imageBundle: ''

  tasks:

  # TC3 - Create a 3 tier topology and attach image bundles to one of the containers and remove it.
  # Testing:
  #       1. Creating Test_bundle
  #       2. Adding image bundles
  #       3. Change in image bundles with apply_mode: loose
  #       4. Change in image bundles with apply_mode: strict
  #       5. Removal of container which contains image bundles.
  #       6. Remove entire 3 tier topology in which image bundles is attached to one of the containers
    - name: "Upload image"
      arista.cvp.cv_image_v3:
        mode: image
        action: add
        image: "{{ image_name }}"

    - name: "Create a bundle for test"
      arista.cvp.cv_image_v3:
        mode: bundle
        action: add
        bundle_name: Test_bundle
        image_list:
          - "{{ image_name }}"
      register: create_bundle_data

    - name: "Testing create bundle"
      ansible.builtin.assert:
        that:
          # yamllint disable-line rule:colons
          - create_bundle_data.data.data == "Bundle : Test_bundle successfully created"

    - name: "Create second bundle for test"
      arista.cvp.cv_image_v3:
        mode: bundle
        action: add
        bundle_name: vEOS-lab-4.30.1F
        image_list:
          - "{{ image_name }}"
      register: create_bundle_data_2

    - name: "Testing create bundle"
      ansible.builtin.assert:
        that:
          # yamllint disable-line rule:colons
          - create_bundle_data_2.data.data == "Bundle : vEOS-lab-4.30.1F successfully created"

    - name: Build Container Topology with image bundle On {{ inventory_hostname }}
      arista.cvp.cv_container_v3:
        topology: "{{ topology_3_tier }}"
      register: build_topo_3_tier

    - name: Testing Build Container
      ansible.builtin.assert:
        that:
          - build_topo_3_tier.container_added.changed == true
          - build_topo_3_tier.container_added.container_added_count == 3
          - build_topo_3_tier.container_added.container_added_list == ["TEAM01", "TEAM01_DC", "TEAM01_LEAFS"]
          - build_topo_3_tier.container_added.success == true
          - build_topo_3_tier.bundle_attached.changed == true
          - build_topo_3_tier.bundle_attached.bundle_attached_count == 1
          - build_topo_3_tier.bundle_attached.bundle_attached_list == ["vEOS-lab-4.30.1F"]
          - build_topo_3_tier.bundle_attached.success == true

    - name: "Change Image"
      arista.cvp.cv_container_v3:
        topology: '{{ change_image_container_test_bundle }}'
      register: change_image_test_bundle

    - name: "Testing Change Image"
      ansible.builtin.assert:
        that:
          - change_image_test_bundle.bundle_attached.changed == true
          - change_image_test_bundle.bundle_attached.bundle_attached_count == 1
          - change_image_test_bundle.bundle_attached.bundle_attached_list == ["Test_bundle"]
          - change_image_test_bundle.bundle_attached.success == true

    - name: "Remove Image"
      arista.cvp.cv_container_v3:
        topology: '{{ remove_image }}'
        apply_mode: strict
      register: image_remove

    - name: "Testing Remove Image"
      ansible.builtin.assert:
        that:
          - image_remove.bundle_detached.changed == true
          - image_remove.bundle_detached.bundle_detached_count == 1
          - image_remove.bundle_detached.bundle_detached_list == ["Test_bundle"]
          - image_remove.bundle_detached.success == true

    - name: "Remove Container Topology With Image On {{ inventory_hostname }}"
      arista.cvp.cv_container_v3:
        topology: '{{ image_container }}'
        state: absent
      register: image_container_remove

    - name: "Testing Remove Container With Image"
      ansible.builtin.assert:
        that:
          - image_container_remove.container_deleted.changed == true
          - image_container_remove.container_deleted.container_deleted_count == 1
          - image_container_remove.container_deleted.container_deleted_list == ["TEAM01_LEAFS"]
          - image_container_remove.container_deleted.success == true

    - name: "Add Container Topology With Image On {{ inventory_hostname }}"
      arista.cvp.cv_container_v3:
        topology: '{{ image_container }}'

    - name: Clean-up Topology
      arista.cvp.cv_container_v3:
        topology: '{{ topology_3_tier }}'
        state: absent
      register: delete_topology

    - name: Clean-up Bundle
      arista.cvp.cv_image_v3:
        mode: bundle
        action: remove
        bundle_name: Test_bundle
        image_list:
          - "{{ image_name }}"
      register: delete_bundle

    - name: "Testing Clean-up"
      ansible.builtin.assert:
        that:
          - delete_topology.container_deleted.changed == true
          - delete_topology.container_deleted.container_deleted_count == 3
          - delete_topology.container_deleted.container_deleted_list == ["TEAM01_LEAFS", "TEAM01_DC", "TEAM01"]
          - delete_topology.container_deleted.success == true
          - delete_bundle.data.data == "success"
