---
- name: Remove output folders
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: delete local folders
      delegate_to: 127.0.0.1
      run_once: true
      file:
        path: "{{playbook_dir}}/{{ item }}"
        state: absent
      with_items:
        - documentation
        - config_backup
        - reports
