---
scenario:
  create_sequence:
    - dependency
    - prepare
  converge_sequence:
    - dependency
    - prepare
    - converge
  test_sequence:
    - dependency
    - syntax
    - converge
    - idempotence
    - verify
  cleanup_sequence:
    - destroy
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: dhcp_server01
    image: avdteam/base:3.6
    pre_build_image: true
    managed: false
    groups:
      - TOOLS
provisioner:
  name: ansible
  config_options:
    defaults:
      jinja2_extensions: 'jinja2.ext.loopcontrols,jinja2.ext.do,jinja2.ext.i18n'
      gathering: explicit
      command_warnings: False
  inventory:
    links:
      hosts: 'inventory/hosts'
      group_vars: 'inventory/group_vars/'
      host_vars: 'inventory/host_vars/'
  ansible_args:
    - --inventory=inventory/hosts
verifier:
  name: ansible
  inventory:
    links:
      hosts: 'inventory/hosts'
      group_vars: 'inventory/group_vars/'
      host_vars: 'inventory/host_vars/'
  ansible_args:
    - --inventory=inventory/hosts
  config_options:
    defaults:
      jinja2_extensions: 'jinja2.ext.loopcontrols,jinja2.ext.do,jinja2.ext.i18n'
      gathering: explicit
      command_warnings: False
