# markdownlint configuration
# the definitive list of rules for markdownlint can be found:
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
#
# only deviations from the defaults are noted here or where there's an opinion
# being expressed.

# default state for all rules
default:
  true

# heading style
MD003:
  style: "atx"

# unordered list style
MD004:
  style: "dash"

# unorderd list indentation (2-spaces)
# keep it tight yo!
MD007:
  indent: 2

# line length
MD013:
  false
  # a lot of debate whether to wrap or not wrap

# multiple headings with the same content
# siblings_only is set here to allow for common header values in structured
# documents
MD024:
  siblings_only: true

# MD029/ol-prefix - Ordered list item prefix
MD029:
  # List style
  style: "ordered"

# fenced code  should be surrounded by blank lines default: true
MD031:
  true

# lists should be surrounded by blank lines default: true
MD032:
  true

# MD033/no-inline-html - Inline HTML
MD033:
  false

# bare URL - bare URLs should be wrapped in angle brackets
# <https://eos.arista.com>
MD034:
  false

# horizontal rule style default: consistent
MD035:
  style: "---"

# first line in a file to be a top-level heading
# since we're using front-matter, this
MD041:
  false


# proper-names - proper names to have the correct capitalization
# probably not entirely helpful in a technical writing environment.
MD044:
  false

# block style - disabled to allow for admonitions
MD046:
  false

# MD048/code-fence-style - Code fence style
MD048:
  # Code fence style
  style: "backtick"

# MD049/Emphasis style should be consistent
MD049:
  # Emphasis style should be consistent
  style: "asterisk"

# MD050/Strong style should be consistent
MD050:
  # Strong style should be consistent
  style: "asterisk"
