#!/bin/sh

# Create a link to this file at .git/hooks/pre-commit to
# force PEP8 validation prior to committing:
#
# $ ln -s -f ../../.github/pre-commit .git/hooks/pre-commit
#
# Ignored violations:
#
#   E402: Module level import not at top of file
#   E741: Do not use variables named 'l', 'o', or 'i'
#   W503: Line break occurred before a binary operator
#   W504: Line break occurred after a binary operator

exec 1>&2

echo "Validating PEP8 compliance..."
echo "------------------------------------------------------------------------------------------------------------"
echo "  - Modules validation"
python -m pylint --jobs 0 --reports n --output-format=parseable --max-line-length 160 --ignore E402,E741,W503,W504 arista/cvp/plugins/modules/*.py
echo "------------------------------------------------------------------------------------------------------------"
echo "  - Module Utils validation"
python -m pylint --jobs 0 --reports n --output-format=parseable --max-line-length 160 --ignore E402,E741,W503,W504 arista/cvp/plugins/module_utils/*.py