---
ansible_collections/arista/cvp/roles/**/*:
  - sugetha24
ansible_collections/arista/cvp/plugins/**/*:
  - guillaumeVilar
  - sugetha24
  - noredistribution
ansible_collections/arista/cvp/molecule/**/*:
  - guillaumeVilar
  - sugetha24
  - noredistribution
ansible_collections/arista/cvp/docs/**/*:
  - sugetha24
.github/**:
  - sugetha24
