# execution-environment.yml
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:latest'

dependencies:
  galaxy: ansible_collections/arista/cvp/collections.yml
  python: ansible_collections/arista/cvp/requirements.txt

additional_build_steps:
  prepend: |
    RUN pip install --upgrade pip setuptools
    RUN yum install -y \
        make \
        wget \
        curl \
        less \
        git \
        vim \
        sshpass
  append:
    - COPY ansible_collections/arista/cvp/ /usr/share/ansible/collections/ansible_collections/arista/cvp
    - RUN ls -la /usr/share/ansible/collections/ansible_collections/arista
