# execution-environment.yml
# Used to create image from cloned directory instead of galaxy
# Run from root of repo
# Example:
#   ansible-builder build --container-runtime=docker --tag=arista-cvp-runner --verbosity 3 -c .
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:stable-2.12-latest'
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--force --verbose'

dependencies:
  galaxy: ansible_collections/arista/cvp/collections.yml
  python: ansible_collections/arista/cvp/requirements.txt
  system: ansible_collections/arista/cvp/bindep.txt

additional_build_steps:
  append:
    - COPY ansible_collections/arista/cvp/ /usr/share/ansible/collections/ansible_collections/arista/cvp
