# execution-environment.yml
# Referenced when this collection is part of a larger execution-environment
---
version: 1

dependencies:
  galaxy: collections.yml
  python: requirements.txt
  system: bindep.txt
