---
scenario:
  test_sequence:
    - syntax
    - create
    - converge
    # - verify
driver:
  name: docker
platforms:
  - name: cv_server
    image: avdteam/base:3.6-v1.0
    pre_build_image: true
    managed: true
    groups:
      - CVP
provisioner:
  name: ansible
  config_options:
    defaults:
      jinja2_extensions: 'jinja2.ext.loopcontrols,jinja2.ext.do,jinja2.ext.i18n'
      gathering: explicit
      command_warnings: False
      remote_tmp: /tmp/.ansible-${USER}/tmp
  inventory:
    links:
      hosts: 'inventory/hosts.yml'
      group_vars: 'inventory/group_vars/'
      host_vars: 'inventory/host_vars/'
  ansible_args:
    - --inventory=inventory/hosts.yml
    - --check
verifier:
  name: ansible
  inventory:
    links:
      hosts: 'inventory/hosts.yml'
      group_vars: 'inventory/group_vars/'
      host_vars: 'inventory/host_vars/'
  ansible_args:
    - --inventory=inventory/hosts.yml
  config_options:
    defaults:
      jinja2_extensions: 'jinja2.ext.loopcontrols,jinja2.ext.do,jinja2.ext.i18n'
      gathering: explicit
      command_warnings: False
