name: Bug Report
description: Report a bug impacting CV collection
title: "Bug Report Title"
labels: ['type: bug', triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: issue-summary
    attributes:
      label: Issue Summary
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "please detail your issue"
    validations:
      required: true

  - type: dropdown
    id: component_v1
    attributes:
      label: Which component(s) of AVD impacted
      multiple: false
      options:
        - cv_device_v3
        - cv_container_v3
        - cv_configlet_v3
        - cv_task_v3
        - cv_tag_v3
        - cv_facts_v3
        - cv_image_v3
        - cv_change_control_v3
        - other

  - type: dropdown
    id: runner
    attributes:
      label: How do you run AVD ?
      multiple: false
      options:
        - Ansible CLI (with virtual-env or native python)
        - Ansible CLI with AVD Runner
        - Ansible AWX

  - type: textarea
    id: user_var
    attributes:
      label: Input variables
      description: Please copy and paste any relevant YAML data to reproduce your issue.
      render: yaml

  - type: textarea
    id: step-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please copy and paste any relevant inputs to reproduce your issue.
      render: shell

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output from the debug logs. This will be automatically formatted into code.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://avd.sh/en/latest/docs/contribution/overview.html)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
