---
all:
  children:
    CVP:
      hosts:
        CloudVision:
          # ansible_httpapi_host: 192.168.0.5
          # ansible_host: 192.168.0.5
          ansible_httpapi_host: validateconfig-1-fcb9351a.topo.testdrive.arista.com
          ansible_host: validateconfig-1-fcb9351a.topo.testdrive.arista.com
          ansible_user: arista
          ansible_password: aristast7i
          ansible_connection: httpapi
          ansible_httpapi_use_ssl: True
          ansible_httpapi_validate_certs: False
          ansible_network_os: eos
          ansible_httpapi_port: 443
          # Configuration to get Virtual Env information
          ansible_python_interpreter: $(which python3)
