---
- name: cv_configlet_v3
  hosts: CloudVision
  connection: local
  gather_facts: no
  vars:
    CVP_CONFIGLETS:
      configlet1: 'alias a{{ 999 | random }} show lldp'
      configlet2: 'alias c{{ 999 | random }} show version'

  tasks:
    - name: "Delete config"
      arista.cvp.cv_configlet_v3:
        configlets: "{{CVP_CONFIGLETS}}"
        state: absent

    - name: 'Collect devices facts from {{inventory_hostname}}'
      arista.cvp.cv_facts_v3:
        facts:
          - configlets
        regexp_filter: "configlet"
      register: FACTS_CONFIGLET

    - name: 'Display cv_configlet result'
      debug:
        msg: '{{FACTS_CONFIGLET}}'
