---
- name: CVP Change Control Test show unknown
  hosts: cv_server
  gather_facts: false
  vars:
    change:
      name: Leaf 1A Change Control
      notes: Created via playbook
      activities:
        - action: "mlaghealthcheck"
          name: Check_LEAF1A_MLAG_Health
          arguments:
            - name: DeviceID
              value: SN-DC1-POD1-LEAF1A
          stage: LEAF1A_MLAG_Health
      stages:
        - name: LEAF1A_MLAG_Health
          mode: parallel

  tasks:
    - name: "Show an unknown change control on {{inventory_hostname}} using change_id field - this should fail"
      arista.cvp.cv_change_control_v3:
        state: show
        change_id: ["1234567890"]
      register: cv_show_unknown_id

    - name: "Print out the change control}"
      debug:
        msg: "{{ cv_show_unknown_id }}"

    - name: "Show an unknown change control on {{inventory_hostname}} using change control name - this should fail"
      arista.cvp.cv_change_control_v3:
        state: show
        name: "Unknown-CC-1234567890"
      register: cv_show_unknown_name

    - name: "Print out the change control}"
      debug:
        msg: "{{ cv_show_unknown_name }}"
