---
- name: CVP Change Control Test remove unknown
  hosts: cv_server
  gather_facts: false
  vars:
    change:
      name: Leaf 1A Change Control
      notes: Created via playbook
      activities:
        - action: "mlaghealthcheck"
          name: Check_LEAF1A_MLAG_Health
          arguments:
            - name: DeviceID
              value: SN-DC1-POD1-LEAF1A
          stage: LEAF1A_MLAG_Health
      stages:
        - name: LEAF1A_MLAG_Health
          mode: parallel

  tasks:
    - name: "Remove an unknown change control on {{inventory_hostname}} using change_id field - this should fail"
      arista.cvp.cv_change_control_v3:
        state: remove
        change_id: ["Unknown-1234567890}"]
