---
- name: CVP Change Control Test create followed by show
  hosts: cv_server
  gather_facts: false
  vars:
    change:
      name: Leaf 1A Change Control
      notes: Created via playbook
      activities:
        - action: "mlaghealthcheck"
          name: Check_LEAF1A_MLAG_Health
          arguments:
            - name: DeviceID
              value: SN-DC1-POD1-LEAF1A
          stage: LEAF1A_MLAG_Health
      stages:
        - name: LEAF1A_MLAG_Health
          mode: parallel

  tasks:
    - name: "Create a change control on {{inventory_hostname}}"
      arista.cvp.cv_change_control_v3:
        state: set
        change: "{{ change }}"
      register: cv_change_control_test

    - name: "Show a change control on {{inventory_hostname}} using change_id field"
      arista.cvp.cv_change_control_v3:
        state: show
        change_id: ["{{ cv_change_control_test.data.id }}"]
      register: cv_show_cc_by_id

    - name: "Print out the change control}"
      debug:
        msg: "{{ cv_show_cc_by_id }}"

    - name: "Show a change control on {{inventory_hostname}} using CC name"
      arista.cvp.cv_change_control_v3:
        state: show
        name: "{{ change.name }}"
      register: cv_show_cc_by_name

    - name: "Print out the change control}"
      debug:
        msg: "{{ cv_show_cc_by_name }}"
