# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
---
# tasks file for ztp-setup
# If mode=online launch server configuration
# If mode=offline generate dhcpd.conf to {{output_dir}}
- name: Start creation/update process.
  tags: [provision]
  include_tasks: "./{{ mode }}.yml"
