---
- name: gather os specific variables for Centos / Red Hat OS
  include_vars: "centos-{{ansible_distribution_major_version}}.yml"
  when: ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux'

- name: gather os specific variables for Debian / Ubuntu OS
  include_vars: "debian.yml"
  when: ansible_distribution == "Debian" or ansible_distribution == 'Ubuntu'

- name: update packages list
  apt:
    update_cache: yes
  when: ansible_distribution == "Debian" or ansible_distribution == 'Ubuntu'

- name: install packages
  become: true
  package:
    name: "{{ dhcp_packages }}"
    state: "{{ dhcp_packages_state }}"

- include_tasks: fix-debian.yml
  when: ansible_distribution == "Debian" or ansible_distribution == 'Ubuntu'

- name: 'generate DHCPd configuration file'
  become: true
  template:
    src: 'dhcpd.conf.j2'
    dest: '{{ dhcp_config }}'
    backup: yes
  notify: "restart dhcpd"

- name: check & activate DHCP service
  become: true
  service:
    name: '{{ dhcp_service }}'
    enabled: yes
    state: started
