- name: Test cv_tag_v3
  hosts: CloudVision
  connection: local
  gather_facts: no
  vars:
    CVP_TAGS:
      # - device_id: leaf1
      - device: leaf1.atd.lab
        device_tags:
          - name: leaf1DTag1_new
            value: leaf1DVal1_new
      - device_id: leaf2
      # - device: leaf2.atd.lab
        device_tags:
          - name: leaf2DTag1_new
            value: leaf2DVal1_new
  tasks:
    - name: assign/unassign non-existing device tags
      arista.cvp.cv_tag_v3:
        tags: "{{CVP_TAGS}}"
        mode: assign
        auto_create: true
