- name: Test cv_tag_v3
  hosts: CloudVision
  connection: local
  gather_facts: no
  vars:
    CVP_TAGS:
      - device_id: leaf1
      # - device: leaf1.atd.lab
        device_tags:
          - name: d_t2
            value: 123
  tasks:
    - name: create tags
      arista.cvp.cv_tag_v3:
        tags: "{{CVP_TAGS}}"
        # mode: unassign
        mode: assign
