- name: Test cv_tag_v3
  hosts: CloudVision
  connection: local
  gather_facts: no
  vars:
    CVP_TAGS:
      # - device_id: leaf1
      - device: leaf1.atd.lab
        device_tags:
          - name: leaf1DTag1
            value: leaf1DVal1
      # - device: leaf2.atd.lab
      - device_id: leaf2
        device_tags:
          - name: leaf2DTag1
            value: leaf2DVal1
  tasks:
    - name: assign/unassign existing device tags
      arista.cvp.cv_tag_v3:
        tags: "{{CVP_TAGS}}"
        mode: assign
        # mode: unassign
