- name: Test cv_tag_v3
  hosts: CloudVision
  connection: local
  gather_facts: no
  vars:
    CVP_TAGS_CREATE:
      - device_tags:
          - name: leaf1DTag1
            value: leaf1DVal1
          - name: leaf2DTag1
            value: leaf2DVal1
      - interface_tags:
          - tags:
              - name: leaf1IntfTag1
                value: leaf1IntfVal1
              - name: leaf1IntfTag2
                value: leaf1IntfVal2
              - name: leaf2IntfTag1
                value: leaf2IntfVal1
    CVP_TAGS_ASSIGN_DEVICE:
          - device: leaf1.atd.lab
            device_tags:
              - name: leaf1DTag1
                value: leaf1DVal1
          - device_id: leaf2
            device_tags:
              - name: leaf2DTag1
                value: leaf2DVal1
    CVP_TAGS_ASSIGN_INTERFACE:
      - device: leaf1.atd.lab
        interface_tags:
          - tags:
            - name: leaf1IntfTag1
              value: leaf1IntfVal1
            interface: Ethernet1
          - tags:
            - name: leaf1IntfTag2
              value: leaf1IntfVal2
            interface: Ethernet2
      - device_id: leaf2
        interface_tags:
          - tags:
            - name: leaf2IntfTag1
              value: leaf2IntfVal1
            interface: Ethernet1
    CVP_TAGS_AUTOCREATE_DEVICE:
      - device: leaf1.atd.lab
        device_tags:
          - name: leaf1DTag1_new
            value: leaf1DVal1_new
      - device_id: leaf2
        device_tags:
          - name: leaf2DTag1_new
            value: leaf2DVal1_new
    CVP_TAGS_AUTOCREATE_INTERFACE:
      - device: leaf1.atd.lab
        interface_tags:
          - tags:
            - name: leaf1IntfTag1_new
              value: leaf1IntfVal1_new
            interface: Ethernet1
          - tags:
            - name: leaf1IntfTag2_new
              value: leaf1IntfVal2_new
            interface: Ethernet2
      - device_id: leaf2
        interface_tags:
          - tags:
            - name: leaf2IntfTag1_new
              value: leaf2IntfVal1_new
            interface: Ethernet1
  tasks:
    - name: create device and interface tags
      arista.cvp.cv_tag_v3:
        tags: "{{CVP_TAGS_CREATE}}"
        mode: create

    - name: assign existing device tags
      arista.cvp.cv_tag_v3:
        tags: "{{CVP_TAGS_ASSIGN_DEVICE}}"
        mode: assign

    - name: assign existing interface tags
      arista.cvp.cv_tag_v3:
        tags: "{{CVP_TAGS_ASSIGN_INTERFACE}}"
        mode: assign

    - name: unassign existing device tags
      arista.cvp.cv_tag_v3:
        tags: "{{CVP_TAGS_ASSIGN_DEVICE}}"
        mode: unassign

    - name: unassign existing interface tags
      arista.cvp.cv_tag_v3:
        tags: "{{CVP_TAGS_ASSIGN_INTERFACE}}"
        mode: unassign

    - name: delete device and interface tags
      arista.cvp.cv_tag_v3:
        tags: "{{CVP_TAGS_CREATE}}"
        mode: delete

    - name: assign/unassign non-existing device tags
      arista.cvp.cv_tag_v3:
        tags: "{{CVP_TAGS_AUTOCREATE_DEVICE}}"
        mode: assign
        auto_create: true

    - name: assign/unassign non-existing interface tags
      arista.cvp.cv_tag_v3:
        tags: "{{CVP_TAGS_AUTOCREATE_INTERFACE}}"
        mode: assign
        auto_create: true

    - name: CLEANUP - unassign device tags
      arista.cvp.cv_tag_v3:
        tags: "{{CVP_TAGS_AUTOCREATE_DEVICE}}"
        mode: unassign

    - name: CLEANUP - delete device tags
      arista.cvp.cv_tag_v3:
        tags: "{{CVP_TAGS_AUTOCREATE_DEVICE}}"
        mode: delete

    - name: CLEANUP - unassign interface tags
      arista.cvp.cv_tag_v3:
        tags: "{{CVP_TAGS_AUTOCREATE_INTERFACE}}"
        mode: unassign

    - name: CLEANUP - delete interface tags
      arista.cvp.cv_tag_v3:
        tags: "{{CVP_TAGS_AUTOCREATE_INTERFACE}}"
        mode: delete
